/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_alternativetags.c"
#include "bar_anybar.c"
#include "bar_dwmblocks.c"
#include "bar_ewmhtags.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statusbutton.c"
#include "bar_statuscmd.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_systray.c"
#include "bar_layoutmenu.c"

/* Other patches */
#include "attachx.c"
#include "autostart.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "decorationhints.c"
#include "dwmc.c"
#include "fullscreen.c"
#include "mpdcontrol.c"
#include "movestack.c"
#include "pertag.c"
#include "push.c"
#include "rotatestack.c"
#include "roundedcorners.c"
#include "scratchpad_alt_1.c"
#include "selfrestart.c"
#include "swallow.c"
#include "vanitygaps.c"
#include "xkb.c"
#include "xrdb.c"
/* Layouts */
#include "layout_flextile-deluxe.c"
