/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "bar_alternativetags.h"
#include "bar_anybar.h"
#include "bar_dwmblocks.h"
#include "bar_ewmhtags.h"
#include "combo.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statusbutton.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_systray.h"
#include "bar_layoutmenu.h"

/* Other patches */
#include "attachx.h"
#include "autostart.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "decorationhints.h"
#include "dwmc.h"
#include "fullscreen.h"
#include "mpdcontrol.h"
#include "movestack.h"
#include "pertag.h"
#include "push.h"
#include "rotatestack.h"
#include "roundedcorners.h"
#include "scratchpad_alt_1.h"
#include "selfrestart.h"
#include "swallow.h"
#include "vanitygaps.h"
#include "xkb.h"
#include "xrdb.h"
/* Layouts */
#include "layout_flextile-deluxe.h"
