/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "bar_alternativetags.h"
#include "bar_anybar.h"
#include "bar_dwmblocks.h"
#include "bar_ewmhtags.h"
#include "combo.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_statusbutton.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_systray.h"
#include "bar_layoutmenu.h"

/* Other patches */
#include "attachx.h"
#include "autostart.h"
#include "cmdcustomize.h"
#include "cyclelayouts.h"
#include "decorationhints.h"
#include "dwmc.h"
#include "fullscreen.h"
#include "inplacerotate.h"
#include "ipc.h"
#include "ipc/ipc.h"
#include "ipc/util.h"
#include "mpdcontrol.h"
#include "movestack.h"
#include "pertag.h"
#include "placemouse.h"
#include "rotatestack.h"
#include "selfrestart.h"
#ifdef XINERAMA
#include "sortscreens.h"
#endif // XINERAMA
#include "swallow.h"
#include "tagallmon.h"
#include "vanitygaps.h"
#include "xkb.h"
#include "xrdb.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_bstackhoriz.h"
#include "layout_centeredmaster.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_deck.h"
#include "layout_grid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

